-- MySQL Script generated by MySQL Workbench
-- Wed Nov 15 22:13:04 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BD-HOUSECLIC
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BD-HOUSECLIC` ;

-- -----------------------------------------------------
-- Schema BD-HOUSECLIC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD-HOUSECLIC` DEFAULT CHARACTER SET utf8 ;
USE `BD-HOUSECLIC` ;

-- -----------------------------------------------------
-- Table `BD-HOUSECLIC`.`District`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-HOUSECLIC`.`District` (
  `CodeDistrict` INT NOT NULL,
  `NameDistrict` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`CodeDistrict`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-HOUSECLIC`.`DetailSchedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-HOUSECLIC`.`DetailSchedule` (
  `CodeDetailSchedule` INT NOT NULL,
  `StartSchedule` CHAR(5) NOT NULL,
  `EndSchedule` CHAR(5) NOT NULL,
  PRIMARY KEY (`CodeDetailSchedule`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-HOUSECLIC`.`Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-HOUSECLIC`.`Contract` (
  `CodeContract` INT NOT NULL,
  `DateContract` DATETIME NOT NULL,
  `TotalCostContract` DECIMAL(10,0) NOT NULL,
  `StateContract` VARCHAR(15) NOT NULL,
  `AssistanceReason` TEXT(45) NOT NULL,
  `RatingScore` DECIMAL(10,0) NOT NULL,
  `RatingState` DECIMAL(10,0) NOT NULL,
  `RatingCommentary` TEXT(45) NULL,
  PRIMARY KEY (`CodeContract`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-HOUSECLIC`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-HOUSECLIC`.`Answer` (
  `CodeAnswer` INT NOT NULL,
  `Technician_CodeTechnician` INT NOT NULL,
  `CodeClient` INT NOT NULL,
  `DateAnswer` DATETIME NOT NULL,
  `CommentAnswer` TEXT(45) NOT NULL,
  `PriceAnswer` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`CodeAnswer`),
  CONSTRAINT `fk_Answer_Technician1`
    FOREIGN KEY (`Technician_CodeTechnician`)
    REFERENCES `BD-HOUSECLIC`.`Technician` (`CodeTechnician`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Answer_Technician1_idx` ON `BD-HOUSECLIC`.`Answer` (`Technician_CodeTechnician` ASC);


-- -----------------------------------------------------
-- Table `BD-HOUSECLIC`.`Quotation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-HOUSECLIC`.`Quotation` (
  `CodeQuotation` INT NOT NULL,
  `Answer_CodeAnswer` INT NOT NULL,
  `TitleSubject` VARCHAR(50) NOT NULL,
  `DetailSubject` TEXT(45) NOT NULL,
  `PhotoSubject` TEXT(45) NULL,
  `VisitCost` DECIMAL(10,0) NOT NULL,
  `AddressSubject` TEXT(45) NOT NULL,
  `StartSubject` CHAR(5) NOT NULL,
  `EndSubject` CHAR(5) NOT NULL,
  `DateSubject` DATETIME NOT NULL,
  `StateQuotation` VARCHAR(15) NOT NULL,
  `CountAnswerQuotation` INT NOT NULL,
  PRIMARY KEY (`CodeQuotation`),
  CONSTRAINT `fk_Quotation_Answer1`
    FOREIGN KEY (`Answer_CodeAnswer`)
    REFERENCES `BD-HOUSECLIC`.`Answer` (`CodeAnswer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Quotation_Answer1_idx` ON `BD-HOUSECLIC`.`Quotation` (`Answer_CodeAnswer` ASC);


-- -----------------------------------------------------
-- Table `BD-HOUSECLIC`.`TypeQuotation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-HOUSECLIC`.`TypeQuotation` (
  `CodeTypeQuotation` INT NOT NULL,
  `Quotation_CodeQuotation` INT NOT NULL,
  `NameTypeQ` VARCHAR(20) NOT NULL,
  `DescriptionTypeQ` TEXT(45) NULL,
  PRIMARY KEY (`CodeTypeQuotation`),
  CONSTRAINT `fk_TypeQuotation_Quotation1`
    FOREIGN KEY (`Quotation_CodeQuotation`)
    REFERENCES `BD-HOUSECLIC`.`Quotation` (`CodeQuotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TypeQuotation_Quotation1_idx` ON `BD-HOUSECLIC`.`TypeQuotation` (`Quotation_CodeQuotation` ASC);


-- -----------------------------------------------------
-- Table `BD-HOUSECLIC`.`Technician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-HOUSECLIC`.`Technician` (
  `CodeTechnician` INT NOT NULL,
  `District_CodeDistrict` INT NOT NULL,
  `DetailSchedule_CodeDetailSchedule` INT NOT NULL,
  `Contract_CodeContract` INT NOT NULL,
  `TypeQuotation_CodeTypeQuotation` INT NOT NULL,
  `NameTech` VARCHAR(30) NOT NULL,
  `LastNameTech` VARCHAR(35) NOT NULL,
  `DniTech` CHAR(8) NOT NULL,
  `AgeTech` INT NOT NULL,
  `CellPhoneTech` CHAR(9) NOT NULL,
  `DescriptionTech` TEXT(45) NULL,
  `PhotoTech` TEXT(45) NULL,
  `PasswordTech` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`CodeTechnician`),
  CONSTRAINT `fk_Technician_District`
    FOREIGN KEY (`District_CodeDistrict`)
    REFERENCES `BD-HOUSECLIC`.`District` (`CodeDistrict`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technician_DetailSchedule1`
    FOREIGN KEY (`DetailSchedule_CodeDetailSchedule`)
    REFERENCES `BD-HOUSECLIC`.`DetailSchedule` (`CodeDetailSchedule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technician_Contract1`
    FOREIGN KEY (`Contract_CodeContract`)
    REFERENCES `BD-HOUSECLIC`.`Contract` (`CodeContract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technician_TypeQuotation1`
    FOREIGN KEY (`TypeQuotation_CodeTypeQuotation`)
    REFERENCES `BD-HOUSECLIC`.`TypeQuotation` (`CodeTypeQuotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Technician_District_idx` ON `BD-HOUSECLIC`.`Technician` (`District_CodeDistrict` ASC);

CREATE INDEX `fk_Technician_DetailSchedule1_idx` ON `BD-HOUSECLIC`.`Technician` (`DetailSchedule_CodeDetailSchedule` ASC);

CREATE INDEX `fk_Technician_Contract1_idx` ON `BD-HOUSECLIC`.`Technician` (`Contract_CodeContract` ASC);

CREATE INDEX `fk_Technician_TypeQuotation1_idx` ON `BD-HOUSECLIC`.`Technician` (`TypeQuotation_CodeTypeQuotation` ASC);


-- -----------------------------------------------------
-- Table `BD-HOUSECLIC`.`Job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-HOUSECLIC`.`Job` (
  `CodeJob` INT NOT NULL,
  `NameJob` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`CodeJob`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-HOUSECLIC`.`Especialty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-HOUSECLIC`.`Especialty` (
  `CodeSpecialty` INT NOT NULL,
  `Job_CodeJob` INT NOT NULL,
  `Technician_CodeTechnician` INT NOT NULL,
  `NameSpecialty` VARCHAR(20) NOT NULL,
  `DescriptionSpecialty` TEXT(30) NULL,
  PRIMARY KEY (`CodeSpecialty`),
  CONSTRAINT `fk_Especialty_Job1`
    FOREIGN KEY (`Job_CodeJob`)
    REFERENCES `BD-HOUSECLIC`.`Job` (`CodeJob`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Especialty_Technician1`
    FOREIGN KEY (`Technician_CodeTechnician`)
    REFERENCES `BD-HOUSECLIC`.`Technician` (`CodeTechnician`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Especialty_Job1_idx` ON `BD-HOUSECLIC`.`Especialty` (`Job_CodeJob` ASC);

CREATE INDEX `fk_Especialty_Technician1_idx` ON `BD-HOUSECLIC`.`Especialty` (`Technician_CodeTechnician` ASC);


-- -----------------------------------------------------
-- Table `BD-HOUSECLIC`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-HOUSECLIC`.`Schedule` (
  `CodeSchedule` INT NOT NULL,
  `DetailSchedule_CodeDetailSchedule` INT NOT NULL,
  `FrequencySchedule` VARCHAR(10) NOT NULL,
  `DaysSchedule` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`CodeSchedule`),
  CONSTRAINT `fk_Schedule_DetailSchedule1`
    FOREIGN KEY (`DetailSchedule_CodeDetailSchedule`)
    REFERENCES `BD-HOUSECLIC`.`DetailSchedule` (`CodeDetailSchedule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Schedule_DetailSchedule1_idx` ON `BD-HOUSECLIC`.`Schedule` (`DetailSchedule_CodeDetailSchedule` ASC);


-- -----------------------------------------------------
-- Table `BD-HOUSECLIC`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD-HOUSECLIC`.`Client` (
  `CodeClient` INT NOT NULL,
  `District_CodeDistrict` INT NOT NULL,
  `Contract_CodeContract` INT NOT NULL,
  `TypeQuotation_CodeTypeQuotation` INT NOT NULL,
  `NameClient` VARCHAR(30) NOT NULL,
  `LastNameClient` VARCHAR(35) NOT NULL,
  `AgeClient` INT NOT NULL,
  `CellPhoneClient` CHAR(9) NOT NULL,
  `AddressClient` TEXT(45) NOT NULL,
  `PasswordClient` VARCHAR(30) NOT NULL,
  `PhotoClient` TEXT(30) NULL,
  PRIMARY KEY (`CodeClient`),
  CONSTRAINT `fk_Client_District1`
    FOREIGN KEY (`District_CodeDistrict`)
    REFERENCES `BD-HOUSECLIC`.`District` (`CodeDistrict`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_Contract1`
    FOREIGN KEY (`Contract_CodeContract`)
    REFERENCES `BD-HOUSECLIC`.`Contract` (`CodeContract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_TypeQuotation1`
    FOREIGN KEY (`TypeQuotation_CodeTypeQuotation`)
    REFERENCES `BD-HOUSECLIC`.`TypeQuotation` (`CodeTypeQuotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Client_District1_idx` ON `BD-HOUSECLIC`.`Client` (`District_CodeDistrict` ASC);

CREATE INDEX `fk_Client_Contract1_idx` ON `BD-HOUSECLIC`.`Client` (`Contract_CodeContract` ASC);

CREATE INDEX `fk_Client_TypeQuotation1_idx` ON `BD-HOUSECLIC`.`Client` (`TypeQuotation_CodeTypeQuotation` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
